const films = [
  {
    filmId: 213414,
    title: "lol",
    isAdult: true,
    releaseYear: "2012",
    duration: 312,
    genres: ["string", "horror"],
    poster: "test",
  },
  {
    filmId: 213415,
    title: "lol2",
    isAdult: true,
    releaseYear: "2012",
    duration: 312,
    genres: ["string", "horror"],
    poster: "test",
  },
  {
    filmId: 213416,
    title: "lol3",
    isAdult: true,
    releaseYear: "2012",
    duration: 312,
    genres: ["string", "horror"],
    poster: "test",
  },
  {
    filmId: 213417,
    title: "lol4",
    isAdult: true,
    releaseYear: "2012",
    duration: 312,
    genres: ["string", "horror"],
    poster: "test",
  },
  {
    filmId: 213418,
    title: "lol5",
    isAdult: true,
    releaseYear: "2012",
    duration: 312,
    genres: ["string", "horror"],
    poster: "test",
  },
  {
    filmId: 213419,
    title: "lol6",
    isAdult: true,
    releaseYear: "2012",
    duration: 312,
    genres: ["string", "horror"],
    poster: "test",
  },
  {
    filmId: 213420,
    title: "lol7",
    isAdult: true,
    releaseYear: "2012",
    duration: 312,
    genres: ["string", "horror"],
    poster: "test",
  },
  {
    filmId: 213421,
    title: "lol8",
    isAdult: true,
    releaseYear: "2012",
    duration: 312,
    genres: ["string", "horror"],
    poster: "test",
  },
  {
    filmId: 213422,
    title: "lol9",
    isAdult: true,
    releaseYear: "2012",
    duration: 312,
    genres: ["string", "horror"],
    poster: "test",
  },
  {
    filmId: 213423,
    title: "lol10",
    isAdult: true,
    releaseYear: "2012",
    duration: 312,
    genres: ["string", "horror"],
    poster: "test",
  },
  {
    filmId: 213424,
    title: "lol11",
    isAdult: true,
    releaseYear: "2012",
    duration: 312,
    genres: ["string", "horror"],
    poster: "test",
  },
  {
    filmId: 213425,
    title: "lol12",
    isAdult: true,
    releaseYear: "2012",
    duration: 312,
    genres: ["string", "horror"],
    poster: "test",
  },
];

export { films };
